Removing deprecated function
fkie-cad/common_helper_mongo pull request #2
Opened 2020-02-12 14:38 UTC by jstucke

removed deprecated function

2020-02-12 14:43 UTC, dorpvom commented
# [Codecov](https://codecov.io/gh/fkie-cad/common_helper_mongo/pull/2?src=pr&el=h1) Report
> Merging [#2](https://codecov.io/gh/fkie-cad/common_helper_mongo/pull/2?src=pr&el=desc) into [master](https://codecov.io/gh/fkie-cad/common_helper_mongo/commit/3d7db864d6f5a8e1d65e609a04f05566e83eee09&el=desc) will **not change** coverage by `%`.
> The diff coverage is `n/a`.

[![Impacted file tree graph](https://codecov.io/gh/fkie-cad/common_helper_mongo/pull/2/graphs/tree.svg?width=650&height=150&src=pr&token=OApMvdhPEr)](https://codecov.io/gh/fkie-cad/common_helper_mongo/pull/2?src=pr&el=tree)

```diff
@@            Coverage Diff            @@
##            master        #2   +/-   ##
=========================================
  Coverage   100.00%   100.00%           
=========================================
  Files            6         6           
  Lines          158       149    -9     
=========================================
- Hits           158       149    -9     
```



------

[Continue to review full report at Codecov](https://codecov.io/gh/fkie-cad/common_helper_mongo/pull/2?src=pr&el=continue).
> **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> Powered by [Codecov](https://codecov.io/gh/fkie-cad/common_helper_mongo/pull/2?src=pr&el=footer). Last update [3d7db86...7a7667f](https://codecov.io/gh/fkie-cad/common_helper_mongo/pull/2?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).

2020-02-14 10:05 UTC, weidenba requested changes

2020-02-14 10:05 UTC, weidenba commented on .isort.cfg
> +known_first_party=analysis,compare,helperFunctions,install,intercom,objects,plugins,
We do not have all these dependencies, do we?

2020-02-14 10:05 UTC, weidenba commented on .pylintrc
> +init-hook='import sys; sys.path.append("./src")'
there is no src folder in this project

2020-02-14 10:05 UTC, weidenba commented on .pylintrc
> +ignore-patterns=test/,src/bin
there is no /src/bin to ignore

2020-02-14 10:05 UTC, weidenba commented on common_helper_mongo/.pylintrc
> +[MASTER]
why do we need the pylintrc two times?

2020-02-14 10:05 UTC, weidenba commented on pytest.ini
> +    install.py E402
there is no install.py src/plugins or /bin/

2020-02-26 10:05 UTC, weidenba approved these changes

2020-02-26 10:06 UTC, merged